version: '3.9'


services:
  server:
    build: /
    ports:
      - '8081:8080'
    depends_on:
      my-db:
        condition: service_healthy

  my-db:
    restart: unless-stopped
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 2s
      timeout: 30s
      retries: 10
volumes:
  my-db:
